before:
  hooks:
    - go mod tidy
builds:
- env:
    - GO111MODULE=on
    - CGO_ENABLED=0
  goos:
    - linux
    - windows
  goarch:
    - amd64
  ldflags:
    - -s -w  -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.builtBy=goreleaser
  binary: udpmesh
  main: ./main/main.go
archives:
- replacements:
    386: i386
    amd64: x86_64
  files:
    - configs/*
  format_overrides:
    - goos: windows
      format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
