# Perform the releasing.
name: release
on:
  push:
    tags:
      - '*'
jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Set up go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13

      - name: Checkout
        uses: actions/checkout@v1

      - name: Run goreleaser
        uses: goreleaser/goreleaser-action@v1
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GOPRIVATE: github.com/skysoft-atm/*
